config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end
  delete '/doses/:id', to: "doses#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# Rails.application.routes.draw do
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#   root to: 'cocktails#index'
#   resources :cocktails do
#     resources :doses, only: [:new, :create]
#   end
#   resources :doses, only: [:destroy]
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates :name, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show,:edit,:destroy,:update]

  def index
    @cocktails = Cocktail.all
  end

  def show


  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path

  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)

  end


end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])

    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      # raise
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path

  end

  private

  def dose_params

    params.require(:dose).permit(:description, :ingredient_id)

  end


end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/edit.html.erb
<h1>Edit Page</h1>
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<div class="head" style="background-image: url('<%= image_path 'city-scape.jpg' %>');">
  <h1>Saucy Cocktails</h1>
</div>

<div class="cocktails-index">
  <% @cocktails.each do |cocktail| %>
     <%= link_to cocktail_path(cocktail) do %>
      <div class="cocktail-card">
        <%= cl_image_tag cocktail.photo, height: 200, width: 300, crop: :fill %>
        <p> <%= cocktail.name.capitalize %> <p>
      </div>
    <% end %>
  <% end %>
</div>

<div>
  <%= link_to "Add a cocktail", new_cocktail_path, class:"btn btn-primary" %>
</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cocktails/show.html.erb
<h1>Show Page</h1>

  <h3> <%= @cocktail.name %> </h3>
    <% @cocktail.ingredients.each do |i| %>
    <p> <%= i.name %> </p>
  <% end %>

  <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>



<%= link_to "Update this cocktail", edit_cocktail_path, class: "btn btn-primary" %>
<%= link_to "Delete this cocktail", cocktail_path, method: :delete, class: "btn btn-danger"  %>
<%= link_to "View all cocktails", cocktails_path, class: "btn btn-info"  %>
<%= link_to "Add ingredients", new_cocktail_dose_path(@cocktail), class: "btn btn-info"  %>

app/views/doses/new.html.erb
<h1>New Dose</h1>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>

    <%= f.association :ingredient %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

<!-- <form action="cocktails/1/doses" method="post"></form>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>
  </body>
</html>